package online.ebeinc.ebeos.widgetcompanion;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.view.*;import android.widget.*;
public final class MainActivity extends Activity{
 int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);} TextView t(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);return v;}
 Button b(String s,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setOnClickListener(l);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(54));p.topMargin=dp(10);b.setLayoutParams(p);return b;}
 @Override public void onCreate(Bundle x){super.onCreate(x);getWindow().setStatusBarColor(Color.rgb(12,5,24));ScrollView sv=new ScrollView(this);sv.setBackgroundColor(Color.rgb(12,5,24));LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(24),dp(28),dp(24),dp(28));sv.addView(r);TextView h=t("EBE OS · WIDGET PACK",26,Color.WHITE);h.setTypeface(h.getTypeface(),1);r.addView(h);TextView s=t("v0.9.9 · safe companion for EBE OS v0.9.8",14,Color.rgb(190,150,255));s.setPadding(0,dp(5),0,dp(20));r.addView(s);r.addView(t("Adds nine first-party widgets without replacing EBE OS or touching your Home layout.\n\n• ALLTHINGS140 live server / now playing\n• ALLTHINGS140 compact\n• System Monitor\n• At a Glance\n• Network & VPN\n• Device Health\n• Quick Panels\n• Battery\n• Storage\n\nOpen EBE OS → WIDGETS to place them. Radio status uses the public read-only station status endpoint.",16,Color.rgb(235,228,245)));r.addView(b("REFRESH ALL WIDGETS",v->{WidgetPack.refreshAll(this);Toast.makeText(this,"Widgets refreshed",0).show();}));r.addView(b("OPEN EBE OS",v->open("online.ebeinc.ebeos")));r.addView(b("OPEN ALLTHINGS140 RADIO",v->WidgetPack.openRadio(this)));r.addView(b("GO TO HOME",v->{Intent i=new Intent(Intent.ACTION_MAIN);i.addCategory(Intent.CATEGORY_HOME);startActivity(i);}));TextView f=t("SAFE INSTALL · package online.ebeinc.ebeos.widgetcompanion",12,Color.rgb(120,255,165));f.setPadding(0,dp(20),0,0);r.addView(f);setContentView(sv);WidgetPack.refreshAll(this);}
 void open(String p){Intent i=getPackageManager().getLaunchIntentForPackage(p);if(i!=null)startActivity(i);else Toast.makeText(this,p+" not installed",1).show();}
 @Override protected void onResume(){super.onResume();WidgetPack.refreshAll(this);}
}
