import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
const HERE=path.dirname(fileURLToPath(import.meta.url)); const ROOT=path.resolve(HERE,'..');
const read=rel=>fs.readFileSync(path.join(ROOT,rel),'utf8');
let passed=0; const check=(c,m)=>{assert.ok(c,m);passed++;console.log(`✓ ${m}`)};
console.log('=== ALLTHINGS140 v0.1.43 ROLLOUT HARDENING ===');
const main=read('visuals-app/src/main.js'); const rust=read('visuals-app/src-tauri/src/lib.rs');
const stage=read('radio/room/stage.js'); const green=read('visuals-green/stage.js'); const rt=read('visuals-realtime/app.py');
const app=read('radio/app.js'); const sw=read('radio/sw.js'); const worker=read('radio/_worker.js'); const headers=read('radio/room/_headers');
check(JSON.parse(read('visuals-app/package.json')).version==='0.1.43','workstation version is 0.1.43');
check(main.includes('media.items || media.visualAssets || media.playlist'),'first-run playlist consumes import_default_media items');
check(main.includes('function reconcilePlaylistWithVisualLibrary'),'24/7 playlist reconciles against current Visual Content library');
check(main.includes("assetId: routeId || prior?.assetId"),'reconciled local media adopts its current scanned identity so replaced files cannot reuse stale remote URLs');
check(main.includes('sourcePath: item?.sourcePath') && main.includes('runtimePath: item?.runtimePath'),'local playlist paths reach Tauri preflight only');
check(rust.includes('24/7 PRE-FLIGHT FAILED'),'full publish fails closed when enabled local playlist media cannot be verified');
check(rust.includes('Visual routing confirmation mismatch') && rust.includes('Visual routing returned invalid JSON'),'workstation safety buttons require a persisted routing confirmation before reporting success');
check(rust.includes('playlist_local_path') && rust.includes('safe_playlist_asset_id'),'Rust has deterministic playlist preflight helpers');
check(rust.indexOf('if let Some(path) = local_path.as_deref()') < rust.indexOf('} else if let Some(u) = explicit_url'),'canonical 24/7 URLs prefer verified local runtime media over stale persisted public URLs');
check(rust.includes('media_to_sync.push((local_path, "visuals".to_string()'),'enabled local 24/7 media is staged before canonical publish');
check(rust.includes('let upload_timeout_secs = if is_preview { 15 } else { 90 }'),'full 24/7 uploads get a bounded long timeout without slowing preview tests');
check(main.includes('item.runtimePath || item.sourcePath || item.path'),'Validate All probes reconciled runtime/source paths instead of obsolete path-only entries');
check(main.includes("const mediaIndex = visualLibrary.findIndex(item =>"),'24/7 Preview resolves the selected playlist asset back into the Visual Content library');
check(stage.includes('function fitCompositionCanvas()'),'renderer fits canonical composition to a true design canvas');
check(stage.includes('new ResizeObserver(() => fitCompositionCanvas())'),'renderer refits canonical canvas when its room area changes');
check(stage.includes('function rendererMediaReady()'),'renderer has explicit visual+stage readiness predicate');
check(stage.includes("engageAutomaticLegacyFallback('realtime_unavailable')"),'public Room auto-falls back after a sustained realtime outage');
check(stage.includes("engageAutomaticLegacyFallback('renderer_not_ready')"),'public Room auto-falls back when the compositor cannot become render-ready');
check(stage.includes("activeVideo?.dataset.id || visual?.media?.id"),'normal 24/7 ACK identifies the actually active visual buffer, not only the layout seed asset');
check(stage.includes('stageReadyState'),'ACK includes Stage readiness evidence');
check(!stage.includes("sessionId || 'green-session'"),'renderer no longer invents a fake HTTP ACK session');
check(stage.includes('lastRendererAckKey = ackKey') && stage.indexOf('lastRendererAckKey = ackKey') > stage.indexOf("ws.send(JSON.stringify({ type: 'renderer_ack'"),'ACK dedupe key is set only after a transport send succeeds');
check(rt.includes('renderer_session_not_active'),'HTTP ACK fallback requires an active renderer WebSocket session');
check(rt.includes('layout_hash_not_active'),'renderer ACK cannot certify a stale/non-active layout');
check(rt.includes('renderingCurrentLayout'),'renderer-state exposes strict current-layout render truth');
check(rt.includes('visual_mode == "new"'),'legacy safety heartbeats do not refresh compositor-render ACK freshness');
check(rt.includes('ack.get(\"rendererSessionId\")==sid'),"a different renderer heartbeat cannot refresh another session's ACK");
check(rt.includes('ack_session_live') && rt.includes('rendererClients'),'renderer-state requires the ACKing session to still be live and exposes audience renderer counts');
check(rt.includes('if state.get("is_audience")') && rt.includes('observer_cannot_react'),'operator/staging sockets cannot inflate listener presence or public room energy');
check(main.includes("audience: false") && stage.includes("audience: C.environment === 'live'"),'workstation/Green renderer sockets join as observers while public Room listeners count as audience');
check(main.includes('renderer-state?environment=green-staging'),'Test Current Visual waits specifically for Green staging ACK');
check(headers.includes('wss://chat.ebeinc.online'),'Room CSP allows the existing moderated chat WebSocket');
check(app.includes("navigator.serviceWorker.register('/sw.js'"),'public site explicitly registers the corrected service worker');
check(read('radio/index.html').includes('app.js?v=2.0.1') && sw.includes('app.js?v=2.0.1'),'radio app cache key is bumped so the restored service-worker registration reaches existing browsers');
check(sw.includes('allthings140-radio-v60'),'service worker cache namespace bumped to v60');
check(worker.includes('url.pathname === "/sw.js" || url.pathname === "/sw-v47.js"'),'Worker prevents HTTP caching of both service-worker entry URLs');
check(worker.includes('Visual routing storage unavailable'),'routing writes fail closed instead of falsely succeeding when KV is unbound');
check(worker.includes('raw.chat === "new" ? "new" : "legacy"'),'persisted routing values are normalized fail-safe to legacy');
check(worker.includes('const authError = checkRoutingAuth(request, env);') && worker.includes('mode") === "log"'),'routing audit log is no longer exposed anonymously');
check(stage===green,'Green staging and public Room still share byte-identical compositor JS');
console.log(`${passed}/${passed} v0.1.43 rollout-hardening checks passed`);
