import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';

const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=rel=>fs.readFileSync(path.join(ROOT,rel),'utf8');
let passed=0;
const check=(condition,message)=>{assert.ok(condition,message);passed++;console.log(`✓ ${message}`)};
const worker=read('radio/_worker.js');
const live=read('radio/visuals/live.html');
const cfg=read('radio/visuals/config-live.js');
const roomEngine=read('radio/room/stage.js');
const greenEngine=read('visuals-green/stage.js');
const legacy=read('radio/visuals/index.html');
const legacyRoute=read('radio/visuals/legacy.html');

check(worker.includes('state.visuals === "new" ? "/visuals/live.html" : "/visuals/legacy.html"'),'edge routing selects immutable live or non-index legacy Visuals documents');
check(worker.includes('X-AT140-Visuals-Mode'),'production responses expose the selected Visuals mode');
check(worker.includes('handlePublicVisualsRoutingGet'),'Visuals has a read-only adapter for its independent KV selector');
check(worker.includes('isPublicHost ? state.visuals : "new"'),'Cloudflare preview hosts force only the preview renderer into compositor mode');
check(cfg.includes('environment:"live"') && cfg.includes('ws?environment=live'),'public Visuals registers explicitly as Live');
check(cfg.includes('routingUrl:"/api/visuals-routing"'),'public Visuals reads only its same-origin routing selector');
check(live.includes('../room/stage.js?v=2.5.0'),'public Visuals uses the shared reviewed renderer engine');
check(live.includes('@media(max-width:680px)') && live.includes('.energy{min-width:0') && live.includes('.avatar small{display:none}'),'mobile viewer bounds fixed-size overlays inside the canonical canvas');
check(roomEngine===greenEngine,'Green and public renderers remain byte-identical');
check(roomEngine.includes('}, 25000);') && roomEngine.includes('full 15-second'),'fallback watchdog cannot preempt the bounded cold-media decode budget');
check(legacy.includes('assets/visuals-desktop-v8/index.m3u8'),'legacy fallback preserves the Phase 2 desktop HLS');
check(legacy.includes('phone-visuals-authoritative-v1.mp4'),'legacy fallback preserves the separate mobile Visuals asset');
check(legacyRoute===legacy,'routed legacy document is byte-identical to the Phase 2 Visuals page');
check(read('radio/sw.js')===read('radio/sw-v47.js'),'service worker entry files remain synchronized');
check(read('radio/sw.js').includes('allthings140-radio-v61'),'service worker cache namespace advances for the production cutover');
console.log(`${passed}/${passed} Phase 5 production Visuals checks passed`);
