window.AT140_GREEN_CONFIG={
  environment:"live",
  realtimeUrl:"wss://visuals-realtime-staging.allthings140radio.online/ws?environment=live",
  realtimeStateUrl:"https://visuals-realtime-staging.allthings140radio.online/visuals-state?environment=live",
  realtimeLayoutUrl:"https://visuals-realtime-staging.allthings140radio.online/layout-state?environment=live",
  rendererAckUrl:"https://visuals-realtime-staging.allthings140radio.online/renderer-ack",
  radioStatusUrl:"https://status.ebeinc.online/api/public/status",
  playlistUrl:"../room/playlist.json",
  layoutUrl:"../room/layout.json",
  mediaBaseUrl:"https://visuals-media-staging.allthings140radio.online",
  mediaVersion:"20260816-2",
  routingUrl:"https://allthings140radio.online/api/visuals-routing",
  legacyFallbackEnabled:true,
  legacyFallbackDesktop:"https://allthings140radio.online/assets/visuals-desktop.mp4?v=7.0.0",
  legacyFallbackMobile:"https://allthings140radio.online/assets/phone-visuals-authoritative-v1.mp4?v=1.0.0",
  streamUrl:"https://stream.ebeinc.online/live.mp3"
};
