plugins {
    id 'com.android.application'
}

android {
    namespace 'online.ebeinc.talkietalkie'
    compileSdk 35

    defaultConfig {
        applicationId 'online.ebeinc.talkietalkie'
        minSdk 26
        targetSdk 35
        versionCode 2
        versionName '0.1.1'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
    }
}
