plugins {
    id 'com.android.application'
}

android {
    namespace 'online.ebeinc.talkietalkie'
    compileSdk 35

    defaultConfig {
        applicationId 'online.ebeinc.talkietalkie'
        minSdk 26
        targetSdk 35
        versionCode 5
        versionName '0.1.4'
    }

    signingConfigs {
        familyTest {
            storeFile file('signing/ebe-talkie-family.jks')
            storePassword 'EBETalkieFamily2026!'
            keyAlias 'ebe-talkie'
            keyPassword 'EBETalkieFamily2026!'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.familyTest
        }
        debug {
            minifyEnabled false
            signingConfig signingConfigs.familyTest
        }
    }
}
