(()=>{"use strict";
const STATUS_URLS=["https://status.ebeinc.online/api/public/status","https://status.ebeinc.online/public/status.json","https://stream.ebeinc.online/api/public/status","https://stream.ebeinc.online/public/status.json"];
const $=s=>document.querySelector(s),audio=$("#audio"),heroPlay=$("#heroPlay"),miniPlay=$("#miniPlay"),miniPlayer=$("#miniPlayer"),message=$("#message"),mode=$("#mode"),header=$("#headerStatus"),title=$("#trackTitle"),artist=$("#trackArtist"),listeners=$("#listeners"),timeline=$("#timeline"),elapsed=$("#elapsed"),duration=$("#duration"),next=$("#nextTrack"),footer=$("#footerStatus"),miniTitle=$("#miniTitle"),miniArtist=$("#miniArtist"),miniListeners=$("#miniListeners"),historyEl=$("#trackHistory"),backgroundVideo=$("#backgroundVideo"),liveTakeover=$("#liveTakeover"),volumeControl=$("#volumeControl"),muteControl=$("#muteControl"),miniMute=$("#miniMute"),sleepTimer=$("#sleepTimer"),sleepStatus=$("#sleepStatus");
let latest=null,hls=null,desiredPlay=false,lastTrackId="",stationSchedule=null,reconnectTimer=null,reconnectAttempts=0,deferredInstall=null,sleepUntil=Number(localStorage.getItem("allthings140-sleep-until"))||0,lastVolume=Number(localStorage.getItem("allthings140-volume")||.78);
const fmt=s=>{s=Math.max(0,Math.floor(Number(s)||0));return Math.floor(s/60)+":"+String(s%60).padStart(2,"0")};
const clean=v=>String(v??"").replace(/â€”/g,"—").replace(/â€“/g,"–").replace(/â€™|â€˜/g,"'").replace(/â€œ|â€/g,'"').replace(/Â/g," ").replace(/\s+/g," ").trim();
const trackLabel=s=>clean([s.current_artist,s.current_title].filter(Boolean).join(" — ")||s.current_title||"AllThings140Radio");
function setPlaying(value){document.body.classList.toggle("playing",value);heroPlay.textContent=value?"Ⅱ PAUSE FEED":"▶ CONNECT TO FEED";miniPlay.textContent=value?"Ⅱ":"▶";miniPlay.ariaLabel=value?"Pause station":"Play station";if("mediaSession" in navigator)navigator.mediaSession.playbackState=value?"playing":"paused"}
function setConnecting(value){heroPlay.disabled=value;miniPlay.disabled=value;heroPlay.setAttribute("aria-busy",String(value));if(value){heroPlay.textContent="◌ CONNECTING…";setMsg("Connecting to the live feed…")}}
function pill(text,state){mode.dataset.state=state;header.dataset.state=state;mode.innerHTML="<i></i>"+text;header.innerHTML="<i></i>"+text;document.body.dataset.broadcast=state}
function setMsg(text,kind=""){message.textContent=text;message.className="message "+kind}
function updateClock(){if(latest){const dur=Number(latest.duration_seconds)||0,base=Number(latest.position_seconds)||0,fetched=Number(latest._fetched)||Date.now()/1000,pos=Math.min(dur||Infinity,base+(Date.now()/1000-fetched));elapsed.textContent=fmt(pos);duration.textContent=fmt(dur);timeline.style.width=(dur?Math.min(100,pos/dur*100):0)+"%"}if(stationSchedule){const now=Date.now(),start=Number(stationSchedule.start),end=Number(stationSchedule.end),count=$("#scheduleCountdown");if(now<start){const total=Math.max(0,Math.floor((start-now)/1000)),days=Math.floor(total/86400),hours=Math.floor(total%86400/3600),mins=Math.floor(total%3600/60);count.textContent=`LIVE IN ${days?days+"D ":""}${String(hours).padStart(2,"0")}H ${String(mins).padStart(2,"0")}M`}else if(now<end)count.textContent="● LIVE NOW";else count.textContent="TAKEOVER ENDED"}}
function setVolume(value){const level=Math.max(0,Math.min(1,Number(value)));audio.volume=level;audio.muted=level===0;volumeControl.value=String(Math.round(level*100));if(level>0){lastVolume=level;localStorage.setItem("allthings140-volume",String(level))}const muted=audio.muted;muteControl.textContent=muted?"UNMUTE":"MUTE";miniMute.textContent=muted?"MUTED":"VOL";miniMute.ariaLabel=muted?"Unmute station":"Mute station"}
function toggleMute(){if(audio.muted||audio.volume===0)setVolume(lastVolume>0?lastVolume:.78);else setVolume(0)}
function setSleep(minutes){sleepUntil=minutes?Date.now()+Number(minutes)*60000:0;localStorage.setItem("allthings140-sleep-until",String(sleepUntil));updateSleep()}
function updateSleep(){if(!sleepUntil){sleepStatus.textContent="";sleepTimer.value="0";return}const remaining=sleepUntil-Date.now();if(remaining<=0){sleepUntil=0;localStorage.removeItem("allthings140-sleep-until");sleepTimer.value="0";sleepStatus.textContent="SLEEP TIMER ENDED";desiredPlay=false;audio.pause();setMsg("Sleep timer ended. The station is paused.","good");return}sleepStatus.textContent=`${Math.ceil(remaining/60000)} MIN LEFT`}
window.addEventListener("allthings140:schedule",event=>{stationSchedule=event.detail;$("#scheduleTitle").textContent=stationSchedule.title;$("#scheduleDetail").textContent=`${stationSchedule.host} // ${new Date(stationSchedule.start).toLocaleString()}${stationSchedule.details?" — "+stationSchedule.details:""}`;updateClock()});
function attachStream(url,force=false){if(!url||(!force&&audio.dataset.src===url))return;const resume=desiredPlay||!audio.paused;audio.dataset.src=url;if(hls){hls.destroy();hls=null}audio.removeAttribute("src");audio.load();if(url.includes(".m3u8")&&window.Hls&&Hls.isSupported()){hls=new Hls({liveSyncDurationCount:3,liveMaxLatencyDurationCount:8,maxLiveSyncPlaybackRate:1.25,enableWorker:true});hls.loadSource(url);hls.attachMedia(audio);hls.on(Hls.Events.MANIFEST_PARSED,()=>{reconnectAttempts=0;if(resume)audio.play().catch(()=>setPlaying(false))});hls.on(Hls.Events.ERROR,(_,data)=>{if(!data.fatal)return;if(data.type===Hls.ErrorTypes.NETWORK_ERROR)hls.startLoad();else if(data.type===Hls.ErrorTypes.MEDIA_ERROR)hls.recoverMediaError();else scheduleReconnect()})}else{audio.src=url;if(resume)audio.play().catch(()=>setPlaying(false))}}
function scheduleReconnect(){if(!desiredPlay||reconnectTimer)return;setPlaying(false);setMsg("Stream interrupted. Reconnecting automatically…","bad");const wait=Math.min(12000,1000*2**Math.min(reconnectAttempts++,3));reconnectTimer=setTimeout(()=>{reconnectTimer=null;if(latest)attachStream(latest.hls_url||latest.stream_url,true)},wait)}
function updateMediaSession(label,host){if(!("mediaSession" in navigator))return;navigator.mediaSession.metadata=new MediaMetadata({title:label,artist:host,album:"AllThings140Radio",artwork:[{src:new URL("assets/allthings140-logo-512.png",location.href).href,sizes:"512x512",type:"image/png"}]})}
function apply(s){latest={...s,_fetched:Date.now()/1000};const label=clean(s.current_title||"AllThings140Radio"),host=clean(s.current_artist||(s.mode==="live"?"Live host transmission":"24/7 heavy dubstep"));listeners.textContent=miniListeners.textContent=String(s.listeners||0);title.textContent=miniTitle.textContent=label;artist.textContent=miniArtist.textContent=host;next.textContent=clean([s.next_artist,s.next_title].filter(Boolean).join(" — ")||"—");attachStream(s.hls_url||s.stream_url);updateMediaSession(label,host);const isLive=s.mode==="live"||s.live===true;pill(isLive?"LIVE DJ":"24/7 DUBSTEP",isLive?"live":"autodj");liveTakeover.hidden=!isLive;if(isLive)$("#liveHostName").textContent=host.toUpperCase();footer.textContent=`SYSTEM STATUS: ${isLive?"LIVE DJ":"24/7 HEAVY DUBSTEP"} // ${s.listeners||0} CONNECTED`;setMsg(audio.paused?"Station uplink established. Press play to join the shared transmission.":"Connected to the live feed.","good");updateClock()}
function offline(){pill("OFFLINE","offline");listeners.textContent=miniListeners.textContent="0";title.textContent=miniTitle.textContent="Station uplink unavailable";artist.textContent=miniArtist.textContent="RECONNECTING";liveTakeover.hidden=true;setMsg("The radio relay is reconnecting.","bad");scheduleReconnect()}
async function poll(){let ok=false;for(const endpoint of STATUS_URLS){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),5500);try{const r=await fetch(endpoint+"?t="+Date.now(),{cache:"no-store",signal:ctl.signal});if(!r.ok)throw Error();const s=await r.json();if(!s.online)throw Error();apply(s);ok=true;break}catch{}finally{clearTimeout(timer)}}if(!ok)offline()}
async function toggle(){if(!audio.dataset.src)return setMsg("The feed is reconnecting. Try again shortly.","bad");if(audio.paused){desiredPlay=true;setConnecting(true);try{await audio.play();setPlaying(true);setMsg("Connected to the live feed.","good")}catch{setPlaying(false);setMsg("Press play again once the feed finishes loading.","bad")}finally{setConnecting(false)}}else{desiredPlay=false;audio.pause();setPlaying(false)}}
async function share(){const data={title:"AllThings140Radio",text:latest?`Now playing: ${trackLabel(latest)}`:"Tune into AllThings140Radio",url:"https://ebeinc.online/liveradio/"};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(`${data.text} — ${data.url}`);$("#shareStation").textContent="✓ LINK COPIED";setTimeout(()=>$("#shareStation").textContent="↗ SHARE STATION",1800)}}catch{}}
function setReduced(reduced){document.body.classList.toggle("reduced-motion",reduced);$("#motionToggle").setAttribute("aria-pressed",String(reduced));$("#motionToggle").textContent=reduced?"▶ START VISUALS":"Ⅱ PAUSE VISUALS";$("#motionToggle").title=reduced?"Start background visuals":"Pause background visuals";localStorage.setItem("allthings140-reduced-motion",String(reduced));if(backgroundVideo){if(reduced)backgroundVideo.pause();else backgroundVideo.play().catch(()=>{$("#motionToggle").textContent="▶ TAP FOR VISUALS"})}}
heroPlay.onclick=miniPlay.onclick=toggle;$("#shareStation").onclick=share;$("#motionToggle").onclick=()=>setReduced(!document.body.classList.contains("reduced-motion"));volumeControl.oninput=()=>setVolume(Number(volumeControl.value)/100);muteControl.onclick=miniMute.onclick=toggleMute;sleepTimer.onchange=()=>setSleep(Number(sleepTimer.value));setVolume(Number.isFinite(lastVolume)&&lastVolume>=0?lastVolume:.78);updateSleep();audio.onplaying=()=>{reconnectAttempts=0;setPlaying(true)};audio.onpause=()=>setPlaying(false);audio.onerror=audio.onstalled=scheduleReconnect;window.addEventListener("online",()=>{poll();scheduleReconnect()});document.addEventListener("visibilitychange",()=>{if(!document.hidden&&desiredPlay&&audio.paused)scheduleReconnect()});
if("mediaSession" in navigator){navigator.mediaSession.setActionHandler("play",()=>{desiredPlay=true;toggle()});navigator.mediaSession.setActionHandler("pause",()=>{desiredPlay=false;audio.pause()});navigator.mediaSession.setActionHandler("stop",()=>{desiredPlay=false;audio.pause();audio.currentTime=0})}
window.addEventListener("beforeinstallprompt",event=>{event.preventDefault();deferredInstall=event;$("#installApp").hidden=false});$("#installApp").onclick=async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$("#installApp").hidden=true};window.addEventListener("appinstalled",()=>{$("#installApp").hidden=true});if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(()=>{}));
if(backgroundVideo){backgroundVideo.muted=true;backgroundVideo.defaultMuted=true;backgroundVideo.loop=true;backgroundVideo.playsInline=true;backgroundVideo.addEventListener("playing",()=>{if(!document.body.classList.contains("reduced-motion"))$("#motionToggle").textContent="Ⅱ PAUSE VISUALS"});document.addEventListener("pointerdown",()=>{if(!document.body.classList.contains("reduced-motion")&&backgroundVideo.paused)backgroundVideo.play().catch(()=>{})},{once:true});document.addEventListener("visibilitychange",()=>{if(document.hidden)backgroundVideo.pause();else if(!document.body.classList.contains("reduced-motion"))backgroundVideo.play().catch(()=>{})})}
new IntersectionObserver(([entry])=>{miniPlayer.hidden=entry.isIntersecting},{threshold:.12}).observe($("#listen"));setReduced(localStorage.getItem("allthings140-reduced-motion")==="true");poll();setInterval(poll,5000);setInterval(()=>{updateClock();updateSleep()},500);
})();
