(()=>{"use strict";
const STATUS_URLS=["https://status.ebeinc.online/api/public/status","https://status.ebeinc.online/public/status.json","https://stream.ebeinc.online/api/public/status","https://stream.ebeinc.online/public/status.json"];
const $=s=>document.querySelector(s),audio=$("#audio"),heroPlay=$("#heroPlay"),miniPlay=$("#miniPlay"),miniPlayer=$("#miniPlayer"),message=$("#message"),mode=$("#mode"),header=$("#headerStatus"),title=$("#trackTitle"),artist=$("#trackArtist"),listeners=$("#listeners"),timeline=$("#timeline"),elapsed=$("#elapsed"),duration=$("#duration"),next=$("#nextTrack"),footer=$("#footerStatus"),miniTitle=$("#miniTitle"),miniArtist=$("#miniArtist"),miniListeners=$("#miniListeners"),historyEl=$("#trackHistory"),backgroundVideo=$("#backgroundVideo"),liveTakeover=$("#liveTakeover");
let latest=null,hls=null,desiredPlay=false,lastTrackId="";
const fmt=s=>{s=Math.max(0,Math.floor(Number(s)||0));return Math.floor(s/60)+":"+String(s%60).padStart(2,"0")};
const clean=v=>String(v??"").replace(/â€”/g,"—").replace(/â€“/g,"–").replace(/â€™|â€˜/g,"'").replace(/â€œ|â€/g,'"').replace(/Â/g," ").replace(/\s+/g," ").trim();
const trackLabel=s=>clean([s.current_artist,s.current_title].filter(Boolean).join(" — ")||s.current_title||"AllThings140Radio");
function setPlaying(value){document.body.classList.toggle("playing",value);heroPlay.textContent=value?"Ⅱ PAUSE FEED":"▶ CONNECT TO FEED";miniPlay.textContent=value?"Ⅱ":"▶";miniPlay.ariaLabel=value?"Pause station":"Play station"}
function pill(text,state){mode.dataset.state=state;header.dataset.state=state;mode.innerHTML="<i></i>"+text;header.innerHTML="<i></i>"+text;document.body.dataset.broadcast=state}
function setMsg(text,kind=""){message.textContent=text;message.className="message "+kind}
function updateClock(){if(!latest)return;const dur=Number(latest.duration_seconds)||0,base=Number(latest.position_seconds)||0,fetched=Number(latest._fetched)||Date.now()/1000,pos=Math.min(dur||Infinity,base+(Date.now()/1000-fetched));elapsed.textContent=fmt(pos);duration.textContent=fmt(dur);timeline.style.width=(dur?Math.min(100,pos/dur*100):0)+"%"}
function addHistory(s){const id=String(s.current_track_id??trackLabel(s));if(!id||id===lastTrackId)return;lastTrackId=id;const stored=JSON.parse(localStorage.getItem("allthings140-track-history")||"[]");const entry={id,label:trackLabel(s),ts:Date.now()};const items=[entry,...stored.filter(x=>x.id!==id)].slice(0,10);localStorage.setItem("allthings140-track-history",JSON.stringify(items));renderHistory(items)}
function renderHistory(items=JSON.parse(localStorage.getItem("allthings140-track-history")||"[]")){historyEl.replaceChildren();if(!items.length){const li=document.createElement("li");li.textContent="Track history starts when the station connects.";historyEl.append(li);return}items.forEach((item,index)=>{const li=document.createElement("li"),n=document.createElement("b"),text=document.createElement("span"),time=document.createElement("time");n.textContent=String(index+1).padStart(2,"0");text.textContent=item.label;time.textContent=new Date(item.ts).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"});li.append(n,text,time);historyEl.append(li)})}
function attachStream(url){if(!url||audio.dataset.src===url)return;const resume=desiredPlay||!audio.paused;audio.dataset.src=url;if(hls){hls.destroy();hls=null}audio.removeAttribute("src");audio.load();if(url.includes(".m3u8")&&window.Hls&&Hls.isSupported()){hls=new Hls({liveSyncDurationCount:3,liveMaxLatencyDurationCount:8,maxLiveSyncPlaybackRate:1.25,enableWorker:true});hls.loadSource(url);hls.attachMedia(audio);hls.on(Hls.Events.MANIFEST_PARSED,()=>{if(resume)audio.play().catch(()=>setPlaying(false))});hls.on(Hls.Events.ERROR,(_,data)=>{if(!data.fatal)return;if(data.type===Hls.ErrorTypes.NETWORK_ERROR)hls.startLoad();else if(data.type===Hls.ErrorTypes.MEDIA_ERROR)hls.recoverMediaError();else{hls.destroy();hls=null;setPlaying(false);setMsg("Live feed interrupted. Reconnecting…","bad")}})}else{audio.src=url;if(resume)audio.play().catch(()=>setPlaying(false))}}
function apply(s){latest={...s,_fetched:Date.now()/1000};const label=clean(s.current_title||"AllThings140Radio"),host=clean(s.current_artist||(s.mode==="live"?"Live host transmission":"24/7 heavy dubstep"));listeners.textContent=miniListeners.textContent=String(s.listeners||0);title.textContent=miniTitle.textContent=label;artist.textContent=miniArtist.textContent=host;next.textContent=clean([s.next_artist,s.next_title].filter(Boolean).join(" — ")||"—");attachStream(s.hls_url||s.stream_url);const isLive=s.mode==="live"||s.live===true;pill(isLive?"LIVE DJ":"24/7 DUBSTEP",isLive?"live":"autodj");liveTakeover.hidden=!isLive;if(isLive)$("#liveHostName").textContent=host.toUpperCase();footer.textContent=`SYSTEM STATUS: ${isLive?"LIVE DJ":"24/7 HEAVY DUBSTEP"} // ${s.listeners||0} CONNECTED`;setMsg("Station uplink established. Press play to join the shared transmission.","good");addHistory(s);updateClock()}
function offline(){latest=null;pill("OFFLINE","offline");listeners.textContent=miniListeners.textContent="0";title.textContent=miniTitle.textContent="Station uplink unavailable";artist.textContent=miniArtist.textContent="RECONNECTING";liveTakeover.hidden=true;setMsg("The radio relay is reconnecting.","bad")}
async function poll(){let ok=false;for(const endpoint of STATUS_URLS){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),5500);try{const r=await fetch(endpoint+"?t="+Date.now(),{cache:"no-store",signal:ctl.signal});if(!r.ok)throw Error();const s=await r.json();if(!s.online)throw Error();apply(s);ok=true;break}catch{}finally{clearTimeout(timer)}}if(!ok)offline()}
async function toggle(){if(!audio.dataset.src)return setMsg("The feed is reconnecting. Try again shortly.","bad");if(audio.paused){desiredPlay=true;try{await audio.play();setPlaying(true);setMsg("Connected to the live feed.","good")}catch{setPlaying(false);setMsg("Press play again once the feed finishes loading.","bad")}}else{desiredPlay=false;audio.pause();setPlaying(false)}}
async function share(){const data={title:"AllThings140Radio",text:latest?`Now playing: ${trackLabel(latest)}`:"Tune into AllThings140Radio",url:"https://ebeinc.online/liveradio/"};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(`${data.text} — ${data.url}`);$("#shareStation").textContent="✓ LINK COPIED";setTimeout(()=>$("#shareStation").textContent="↗ SHARE STATION",1800)}}catch{}}
function setReduced(reduced){document.body.classList.toggle("reduced-motion",reduced);$("#motionToggle").setAttribute("aria-pressed",String(reduced));$("#motionToggle").textContent=reduced?"▶ START VISUALS":"Ⅱ PAUSE VISUALS";$("#motionToggle").title=reduced?"Start background visuals":"Pause background visuals";localStorage.setItem("allthings140-reduced-motion",String(reduced));if(backgroundVideo){if(reduced)backgroundVideo.pause();else backgroundVideo.play().catch(()=>{$("#motionToggle").textContent="▶ TAP FOR VISUALS"})}}
heroPlay.onclick=miniPlay.onclick=toggle;$("#shareStation").onclick=share;$("#clearHistory").onclick=()=>{localStorage.removeItem("allthings140-track-history");renderHistory([])};$("#motionToggle").onclick=()=>setReduced(!document.body.classList.contains("reduced-motion"));audio.volume=.78;audio.onplaying=()=>setPlaying(true);audio.onpause=()=>setPlaying(false);audio.onerror=()=>{setPlaying(false);setMsg("Stream interrupted. Retrying automatically…","bad")};
if(backgroundVideo){backgroundVideo.muted=true;backgroundVideo.defaultMuted=true;backgroundVideo.loop=true;backgroundVideo.playsInline=true;backgroundVideo.addEventListener("playing",()=>{if(!document.body.classList.contains("reduced-motion"))$("#motionToggle").textContent="Ⅱ PAUSE VISUALS"});document.addEventListener("pointerdown",()=>{if(!document.body.classList.contains("reduced-motion")&&backgroundVideo.paused)backgroundVideo.play().catch(()=>{})},{once:true});document.addEventListener("visibilitychange",()=>{if(document.hidden)backgroundVideo.pause();else if(!document.body.classList.contains("reduced-motion"))backgroundVideo.play().catch(()=>{})})}
new IntersectionObserver(([entry])=>{miniPlayer.hidden=entry.isIntersecting},{threshold:.12}).observe($("#listen"));setReduced(localStorage.getItem("allthings140-reduced-motion")==="true");renderHistory();poll();setInterval(poll,5000);setInterval(updateClock,500);
})();
