import { DurableObject } from "cloudflare:workers";

interface Env { CHAT_ROOM: DurableObjectNamespace<ChatRoom>; MODERATOR_KEY?: string }
type Color = "purple"|"cyan"|"pink"|"green";
type StoredMessage={id:string;name:string;text:string;ts:number;color:Color;verified:boolean;senderId:string};
type SocketState={id:string;name:string;color:Color;verified:boolean;moderator:boolean;muted:boolean;recent:number[];lastText:string;lastTextAt:number;requestAt?:number};
type Schedule={title:string;host:string;details:string;start:number;end:number};
const ALLOWED_ORIGINS=new Set(["https://allthings140radio.online","https://www.allthings140radio.online","https://ebeinc.online","https://www.ebeinc.online","https://ebeinc-uqt.pages.dev"]),NAME_RE=/[^\p{L}\p{N} _-]/gu,URL_RE=/(?:https?:\/\/|www\.)/gi,BLOCKED_RE=/\b(?:n[i1]gg(?:er|a)|f[a@]gg?[o0]t|k[i1]ke|ch[i1]nk)\b/gi,COLORS=new Set<Color>(["purple","cyan","pink","green"]);
function originAllowed(origin:string|null){return !!origin&&(ALLOWED_ORIGINS.has(origin)||/^https:\/\/[a-z0-9-]+\.ebeinc-uqt\.pages\.dev$/.test(origin)||/^http:\/\/(?:localhost|127\.0\.0\.1)(?::\d+)?$/.test(origin))}
function cleanName(value:unknown,fallback:string){const valueClean=String(value??"").normalize("NFKC").replace(NAME_RE,"").replace(/\s+/g," ").trim().slice(0,24);return valueClean.length>=2?valueClean:fallback}
function cleanMessage(value:unknown){return String(value??"").normalize("NFKC").replace(/[\u0000-\u001f\u007f]/g," ").replace(/\s+/g," ").trim().slice(0,280)}
function json(data:unknown,status=200){return Response.json(data,{status,headers:{"cache-control":"no-store"}})}
async function safeEqual(input:string,secret:string){const enc=new TextEncoder(),a=await crypto.subtle.digest("SHA-256",enc.encode(input)),b=await crypto.subtle.digest("SHA-256",enc.encode(secret));const av=new Uint8Array(a),bv=new Uint8Array(b);let diff=0;for(let i=0;i<av.length;i++)diff|=av[i]^bv[i];return diff===0}

export default {async fetch(request:Request,env:Env){const url=new URL(request.url);if(url.pathname==="/health")return json({ok:true,service:"allthings140-live-chat"});if(url.pathname!=="/ws")return json({error:"Not found"},404);if(request.headers.get("Upgrade")?.toLowerCase()!=="websocket")return json({error:"WebSocket upgrade required"},426);if(!originAllowed(request.headers.get("Origin")))return json({error:"Origin not allowed"},403);return env.CHAT_ROOM.getByName("allthings140-public-v1").fetch(request)}} satisfies ExportedHandler<Env>;

export class ChatRoom extends DurableObject<Env>{
 constructor(ctx:DurableObjectState,env:Env){super(ctx,env);ctx.blockConcurrencyWhile(async()=>{ctx.storage.sql.exec("CREATE TABLE IF NOT EXISTS messages (id TEXT PRIMARY KEY,name TEXT NOT NULL,text TEXT NOT NULL,created_at INTEGER NOT NULL,color TEXT NOT NULL DEFAULT 'purple',verified INTEGER NOT NULL DEFAULT 0,sender_id TEXT NOT NULL DEFAULT '')");const columns=new Set(ctx.storage.sql.exec<{name:string}>("PRAGMA table_info(messages)").toArray().map(row=>row.name));if(!columns.has("color"))ctx.storage.sql.exec("ALTER TABLE messages ADD COLUMN color TEXT NOT NULL DEFAULT 'purple'");if(!columns.has("verified"))ctx.storage.sql.exec("ALTER TABLE messages ADD COLUMN verified INTEGER NOT NULL DEFAULT 0");if(!columns.has("sender_id"))ctx.storage.sql.exec("ALTER TABLE messages ADD COLUMN sender_id TEXT NOT NULL DEFAULT ''");ctx.storage.sql.exec("CREATE INDEX IF NOT EXISTS messages_created_at ON messages(created_at)");ctx.storage.sql.exec("CREATE TABLE IF NOT EXISTS track_history (track_id TEXT PRIMARY KEY,title TEXT NOT NULL,artist TEXT NOT NULL,played_at INTEGER NOT NULL)");ctx.storage.sql.exec("CREATE TABLE IF NOT EXISTS reactions (track_id TEXT NOT NULL,reaction TEXT NOT NULL,voter_id TEXT NOT NULL,PRIMARY KEY(track_id,voter_id))");ctx.storage.sql.exec("CREATE TABLE IF NOT EXISTS requests (id TEXT PRIMARY KEY,title TEXT NOT NULL,artist TEXT NOT NULL,name TEXT NOT NULL,status TEXT NOT NULL,created_at INTEGER NOT NULL)")})}
 async fetch(request:Request){if(request.headers.get("Upgrade")?.toLowerCase()!=="websocket")return json({error:"WebSocket upgrade required"},426);const pair=new WebSocketPair(),[client,server]=Object.values(pair),id=crypto.randomUUID(),fallback=`Listener-${id.slice(0,4).toUpperCase()}`,state:SocketState={id,name:fallback,color:"purple",verified:false,moderator:false,muted:false,recent:[],lastText:"",lastTextAt:0};server.serializeAttachment(state);this.ctx.acceptWebSocket(server);await this.refreshStation();this.sendHistory(server,state);this.broadcast({type:"presence",count:this.ctx.getWebSockets().length});return new Response(null,{status:101,webSocket:client})}
 async webSocketMessage(ws:WebSocket,raw:string|ArrayBuffer){if(typeof raw!=="string"||raw.length>4096)return this.error(ws,"That message is too large.");let body:{type?:unknown;name?:unknown;text?:unknown;color?:unknown;key?:unknown;action?:unknown;messageId?:unknown;senderId?:unknown;schedule?:unknown;reaction?:unknown;trackId?:unknown;title?:unknown;artist?:unknown;requestId?:unknown};try{body=JSON.parse(raw) as typeof body}catch{return this.error(ws,"Invalid message.")}const state=ws.deserializeAttachment() as SocketState|null;if(!state)return ws.close(1011,"Missing session");
  if(body.type==="join"){state.name=cleanName(body.name,state.name);state.color=COLORS.has(body.color as Color)?body.color as Color:"purple";ws.serializeAttachment(state);ws.send(JSON.stringify({type:"joined",name:state.name,color:state.color,verified:state.verified}));return}
  if(body.type==="history"){this.sendHistory(ws,state);return}
  if(body.type==="station_refresh"){await this.refreshStation();this.sendStation(ws,state);return}
  if(body.type==="react"){const reaction=String(body.reaction??""),trackId=String(body.trackId??"").slice(0,100);if(!["fire","skull","vortex"].includes(reaction)||!trackId)return this.error(ws,"Invalid reaction.");this.ctx.storage.sql.exec("INSERT OR REPLACE INTO reactions (track_id,reaction,voter_id) VALUES (?,?,?)",trackId,reaction,state.id);this.broadcastReactions(trackId);return}
  if(body.type==="request"){const now=Date.now();if(state.requestAt&&now-state.requestAt<30000)return this.error(ws,"Wait before sending another request.");const title=cleanMessage(body.title).slice(0,100),artist=cleanMessage(body.artist).slice(0,80);if(!title)return this.error(ws,"Enter a track title.");const request={id:crypto.randomUUID(),title,artist,name:state.name,status:"pending",createdAt:now};this.ctx.storage.sql.exec("INSERT INTO requests (id,title,artist,name,status,created_at) VALUES (?,?,?,?,?,?)",request.id,title,artist,state.name,"pending",now);state.requestAt=now;ws.serializeAttachment(state);this.broadcast({type:"request_added",request});return}
  if(body.type==="moderator_auth"){if(!this.env.MODERATOR_KEY||!await safeEqual(String(body.key??""),this.env.MODERATOR_KEY))return this.error(ws,"Invalid host key.");state.moderator=state.verified=true;state.name="EBMARAH";ws.serializeAttachment(state);ws.send(JSON.stringify({type:"moderator"}));return}
  if(body.type==="schedule_set"){if(!state.moderator)return this.error(ws,"Host access required.");const input=body.schedule as Partial<Schedule>|null,start=Number(input?.start)||0,end=Number(input?.end)||0,schedule:Schedule={title:cleanMessage(input?.title).slice(0,80),host:cleanName(input?.host,"ALLTHINGS140"),details:cleanMessage(input?.details).slice(0,180),start,end};if(!schedule.title||!start||end<=start)return this.error(ws,"Enter a valid title, start, and end time.");await this.ctx.storage.put("schedule",schedule);this.broadcast({type:"schedule",schedule});return}
  if(body.type==="moderate"){if(!state.moderator)return this.error(ws,"Host access required.");return this.moderate(body)}
  if(body.type==="request_action"){if(!state.moderator)return this.error(ws,"Host access required.");const id=String(body.requestId??""),status=String(body.action??"");if(!["approved","dismissed"].includes(status))return this.error(ws,"Invalid request action.");this.ctx.storage.sql.exec("UPDATE requests SET status=? WHERE id=?",status,id);this.broadcast({type:"request_updated",id,status});return}
  if(body.type!=="message")return this.error(ws,"Unknown action.");if(state.muted)return this.error(ws,"You have been muted by a host.");const now=Date.now();state.recent=state.recent.filter(ts=>now-ts<10000);if(state.recent.length>=4||(state.recent.at(-1)&&now-state.recent.at(-1)!<800))return this.error(ws,"Slow down for a moment.");let text=cleanMessage(body.text);if(!text)return this.error(ws,"Type a message first.");if((text.match(URL_RE)??[]).length>1)return this.error(ws,"Only one link is allowed per message.");if(text.toLocaleLowerCase()===state.lastText&&now-state.lastTextAt<30000)return this.error(ws,"Please don’t repeat the same message.");text=text.replace(BLOCKED_RE,"***");const msg:StoredMessage={id:crypto.randomUUID(),name:state.name,text,ts:now,color:state.color,verified:state.verified,senderId:state.id};this.ctx.storage.sql.exec("INSERT INTO messages (id,name,text,created_at,color,verified,sender_id) VALUES (?,?,?,?,?,?,?)",msg.id,msg.name,msg.text,msg.ts,msg.color,msg.verified?1:0,msg.senderId);this.ctx.storage.sql.exec("DELETE FROM messages WHERE id NOT IN (SELECT id FROM messages ORDER BY created_at DESC LIMIT 100)");state.recent.push(now);state.lastText=text.toLocaleLowerCase();state.lastTextAt=now;ws.serializeAttachment(state);this.broadcast({type:"message",message:msg})}
 async webSocketClose(ws:WebSocket,code:number,reason:string){ws.close(code,reason);this.broadcast({type:"presence",count:Math.max(0,this.ctx.getWebSockets().length-1)})}
 async webSocketError(ws:WebSocket){ws.close(1011,"Connection error")}
 private sendHistory(ws:WebSocket,state:SocketState){const rows=[...this.ctx.storage.sql.exec<{id:string;name:string;text:string;created_at:number;color:Color;verified:number;sender_id:string}>("SELECT id,name,text,created_at,color,verified,sender_id FROM messages ORDER BY created_at DESC LIMIT 50")].reverse(),requests=state.moderator?this.ctx.storage.sql.exec<{id:string;title:string;artist:string;name:string;status:string;created_at:number}>("SELECT * FROM requests WHERE status='pending' ORDER BY created_at DESC LIMIT 50").toArray():[];void this.ctx.storage.get<Schedule>("schedule").then(schedule=>ws.send(JSON.stringify({type:"history",messages:rows.map(r=>({id:r.id,name:r.name,text:r.text,ts:r.created_at,color:r.color,verified:!!r.verified,senderId:r.sender_id})),count:this.ctx.getWebSockets().length,name:state.name,schedule:schedule??null,requests:requests.map(r=>({...r,createdAt:r.created_at}))}))).catch(error=>{console.error("chat_history_failed",{error:String(error)});this.error(ws,"Could not load chat history.")});this.sendStation(ws,state)}
 private async refreshStation(){try{const response=await fetch("https://status.ebeinc.online/api/public/status",{headers:{accept:"application/json"}});if(!response.ok)return;const data=await response.json() as {current_track_id?:unknown;current_title?:unknown;current_artist?:unknown};const id=String(data.current_track_id??data.current_title??"").slice(0,100),title=cleanMessage(data.current_title).slice(0,140),artist=cleanMessage(data.current_artist).slice(0,100);if(id&&title){this.ctx.storage.sql.exec("INSERT OR IGNORE INTO track_history (track_id,title,artist,played_at) VALUES (?,?,?,?)",id,title,artist,Date.now());this.ctx.storage.sql.exec("DELETE FROM track_history WHERE track_id NOT IN (SELECT track_id FROM track_history ORDER BY played_at DESC LIMIT 20)")}}catch(error){console.warn("station_refresh_failed",{error:String(error)})}}
 private stationData(state:SocketState){const tracks=this.ctx.storage.sql.exec<{track_id:string;title:string;artist:string;played_at:number}>("SELECT * FROM track_history ORDER BY played_at DESC LIMIT 10").toArray(),current=tracks[0],counts=current?this.ctx.storage.sql.exec<{reaction:string;count:number}>("SELECT reaction,COUNT(*) as count FROM reactions WHERE track_id=? GROUP BY reaction",current.track_id).toArray():[];return{type:"station_data",tracks:tracks.map(t=>({trackId:t.track_id,title:t.title,artist:t.artist,playedAt:t.played_at})),trackId:current?.track_id??"",reactions:Object.fromEntries(counts.map(c=>[c.reaction,c.count])),myReaction:current?this.ctx.storage.sql.exec<{reaction:string}>("SELECT reaction FROM reactions WHERE track_id=? AND voter_id=?",current.track_id,state.id).toArray()[0]?.reaction??null:null}}
 private sendStation(ws:WebSocket,state:SocketState){ws.send(JSON.stringify(this.stationData(state)))}
 private broadcastReactions(trackId:string){const counts=this.ctx.storage.sql.exec<{reaction:string;count:number}>("SELECT reaction,COUNT(*) as count FROM reactions WHERE track_id=? GROUP BY reaction",trackId).toArray();this.broadcast({type:"reactions",trackId,reactions:Object.fromEntries(counts.map(c=>[c.reaction,c.count]))})}
 private moderate(body:{action?:unknown;messageId?:unknown;senderId?:unknown;text?:unknown}){if(body.action==="delete"){const id=String(body.messageId??"");this.ctx.storage.sql.exec("DELETE FROM messages WHERE id=?",id);this.broadcast({type:"deleted",id});return}if(body.action==="clear"){this.ctx.storage.sql.exec("DELETE FROM messages");this.broadcast({type:"cleared"});return}if(body.action==="announce"){const text=cleanMessage(body.text);if(text)this.broadcast({type:"announcement",text});return}if(body.action==="mute"){const senderId=String(body.senderId??"");for(const socket of this.ctx.getWebSockets()){const other=socket.deserializeAttachment() as SocketState|null;if(other?.id===senderId){other.muted=true;socket.serializeAttachment(other);this.error(socket,"A host muted this session.")}}}}
 private error(ws:WebSocket,message:string){ws.send(JSON.stringify({type:"error",message}))}
 private broadcast(payload:unknown){const data=JSON.stringify(payload);for(const socket of this.ctx.getWebSockets())try{socket.send(data)}catch(error){console.warn("chat_broadcast_failed",{error:String(error)})}}
}
