import { DurableObject } from "cloudflare:workers";

interface Env { CHAT_ROOM: DurableObjectNamespace<ChatRoom>; MODERATOR_KEY?: string; SUPABASE_URL?: string; SUPABASE_PUBLIC_KEY?: string }
type Color = "purple" | "cyan" | "pink" | "green";
type StoredMessage = { id: string; name: string; text: string; ts: number; expiresAt: number; color: Color; verified: boolean; senderId: string; avatarPath?: string | null };
type SocketState = { id: string; name: string; color: Color; verified: boolean; moderator: boolean; muted: boolean; recent: number[]; lastText: string; lastTextAt: number; requestAt?: number; authToken?: string; userId?: string; avatarPath?: string | null; accountStatus?: string; blockedIds: string[] };
type Schedule = { title: string; host: string; details: string; start: number; end: number };
const TERMS_VERSION = "green-room-2026-08-21-v1", PUBLIC_TTL = 300000;
const ORIGINS = new Set(["https://allthings140radio.online", "https://www.allthings140radio.online", "https://ebeinc.online", "https://www.ebeinc.online", "https://ebeinc-uqt.pages.dev"]);
const NAME_RE = /[^\p{L}\p{N} _-]/gu, URL_RE = /(?:https?:\/\/|www\.)/gi, BLOCKED_RE = /\b(?:n[i1]gg(?:er|a)|f[a@]gg?[o0]t|k[i1]ke|ch[i1]nk)\b/gi, COLORS = new Set<Color>(["purple", "cyan", "pink", "green"]);
const originAllowed = (origin: string | null) => !!origin && (ORIGINS.has(origin) || /^https:\/\/[a-z0-9-]+\.ebeinc-uqt\.pages\.dev$/.test(origin) || /^http:\/\/(?:localhost|127\.0\.0\.1)(?::\d+)?$/.test(origin));
const cleanName = (v: unknown, fallback: string) => { const value = String(v ?? "").normalize("NFKC").replace(NAME_RE, "").replace(/\s+/g, " ").trim().slice(0, 24); return value.length >= 2 ? value : fallback; };
const cleanMessage = (v: unknown) => String(v ?? "").normalize("NFKC").replace(/[\u0000-\u001f\u007f]/g, " ").replace(/\s+/g, " ").trim().slice(0, 280);
const json = (data: unknown, status = 200) => Response.json(data, { status, headers: { "cache-control": "no-store" } });
async function safeEqual(input: string, secret: string) { const enc = new TextEncoder(), a = await crypto.subtle.digest("SHA-256", enc.encode(input)), b = await crypto.subtle.digest("SHA-256", enc.encode(secret)); const av = new Uint8Array(a), bv = new Uint8Array(b); let diff = 0; for (let i = 0; i < av.length; i++) diff |= av[i] ^ bv[i]; return diff === 0; }

export default { async fetch(request: Request, env: Env) { const url = new URL(request.url); if (url.pathname === "/health") return json({ ok: true, service: "allthings140-live-chat", termsVersion: TERMS_VERSION, publicTtlSeconds: 300 }); if (url.pathname !== "/ws") return json({ error: "Not found" }, 404); if (request.headers.get("Upgrade")?.toLowerCase() !== "websocket") return json({ error: "WebSocket upgrade required" }, 426); if (!originAllowed(request.headers.get("Origin"))) return json({ error: "Origin not allowed" }, 403); return env.CHAT_ROOM.getByName("allthings140-public-v1").fetch(request); } } satisfies ExportedHandler<Env>;

export class ChatRoom extends DurableObject<Env> {
  constructor(ctx: DurableObjectState, env: Env) { super(ctx, env); ctx.blockConcurrencyWhile(async () => { ctx.storage.sql.exec("CREATE TABLE IF NOT EXISTS messages (id TEXT PRIMARY KEY,name TEXT NOT NULL,text TEXT NOT NULL,created_at INTEGER NOT NULL,color TEXT NOT NULL DEFAULT 'purple',verified INTEGER NOT NULL DEFAULT 0,sender_id TEXT NOT NULL DEFAULT '',expires_at INTEGER NOT NULL DEFAULT 0,avatar_path TEXT)"); const cols = new Set(ctx.storage.sql.exec<{ name: string }>("PRAGMA table_info(messages)").toArray().map(r => r.name)); for (const [name, sql] of [["color", "ALTER TABLE messages ADD COLUMN color TEXT NOT NULL DEFAULT 'purple'"], ["verified", "ALTER TABLE messages ADD COLUMN verified INTEGER NOT NULL DEFAULT 0"], ["sender_id", "ALTER TABLE messages ADD COLUMN sender_id TEXT NOT NULL DEFAULT ''"], ["expires_at", "ALTER TABLE messages ADD COLUMN expires_at INTEGER NOT NULL DEFAULT 0"], ["avatar_path", "ALTER TABLE messages ADD COLUMN avatar_path TEXT"]] as const) if (!cols.has(name)) ctx.storage.sql.exec(sql); ctx.storage.sql.exec("UPDATE messages SET expires_at = created_at + 300000 WHERE expires_at = 0"); ctx.storage.sql.exec("CREATE INDEX IF NOT EXISTS messages_created_at ON messages(created_at)"); ctx.storage.sql.exec("CREATE INDEX IF NOT EXISTS messages_expires_at ON messages(expires_at)"); ctx.storage.sql.exec("CREATE TABLE IF NOT EXISTS track_history (track_id TEXT PRIMARY KEY,title TEXT NOT NULL,artist TEXT NOT NULL,played_at INTEGER NOT NULL)"); ctx.storage.sql.exec("CREATE TABLE IF NOT EXISTS reactions (track_id TEXT NOT NULL,reaction TEXT NOT NULL,voter_id TEXT NOT NULL,PRIMARY KEY(track_id,voter_id))"); ctx.storage.sql.exec("CREATE TABLE IF NOT EXISTS requests (id TEXT PRIMARY KEY,title TEXT NOT NULL,artist TEXT NOT NULL,name TEXT NOT NULL,status TEXT NOT NULL,created_at INTEGER NOT NULL)"); await this.purgeExpired(false); }); }
  async fetch(request: Request) { if (request.headers.get("Upgrade")?.toLowerCase() !== "websocket") return json({ error: "WebSocket upgrade required" }, 426); const pair = new WebSocketPair(), [client, server] = Object.values(pair), id = crypto.randomUUID(), fallback = `Listener-${id.slice(0, 4).toUpperCase()}`; const state: SocketState = { id, name: fallback, color: "purple", verified: false, moderator: false, muted: false, recent: [], lastText: "", lastTextAt: 0, blockedIds: [] }; server.serializeAttachment(state); this.ctx.acceptWebSocket(server); await this.refreshStation(); await this.sendHistory(server, state); this.broadcast({ type: "presence", count: this.ctx.getWebSockets().length }); return new Response(null, { status: 101, webSocket: client }); }
  async alarm() { await this.purgeExpired(true); }
  async webSocketMessage(ws: WebSocket, raw: string | ArrayBuffer) { if (typeof raw !== "string" || raw.length > 4096) return this.error(ws, "That message is too large."); let body: any; try { body = JSON.parse(raw); } catch { return this.error(ws, "Invalid message."); } const state = ws.deserializeAttachment() as SocketState | null; if (!state) return ws.close(1011, "Missing session"); await this.purgeExpired(true);
    if (body.type === "auth") return this.authenticate(ws, state, String(body.accessToken || "")); if (body.type === "terms_accept") return this.acceptTerms(ws, state); if (body.type === "post_policy") return this.postPolicy(ws, state); if (body.type === "report") return this.report(ws, state, body); if (body.type === "block" || body.type === "unblock") return this.block(ws, state, body.type === "block", String(body.userId || ""));
    if (body.type === "join") { if (state.userId) return this.error(ws, "Your account username is used in Green Room."); state.name = cleanName(body.name, state.name); state.color = COLORS.has(body.color as Color) ? body.color : "purple"; ws.serializeAttachment(state); ws.send(JSON.stringify({ type: "joined", name: state.name, color: state.color, verified: state.verified })); return; }
    if (body.type === "history") return this.sendHistory(ws, state); if (body.type === "station_refresh") { await this.refreshStation(); return this.sendStation(ws, state); }
    if (body.type === "react") { const reaction = String(body.reaction || ""), trackId = String(body.trackId || "").slice(0, 100); if (!["fire", "skull", "vortex", "heart", "bolt", "bass"].includes(reaction) || !trackId) return this.error(ws, "Invalid reaction."); this.ctx.storage.sql.exec("INSERT OR REPLACE INTO reactions (track_id,reaction,voter_id) VALUES (?,?,?)", trackId, reaction, state.userId || state.id); this.broadcastReactions(trackId); return; }
    if (body.type === "request") { const now = Date.now(); if (state.requestAt && now - state.requestAt < 30000) return this.error(ws, "Wait before sending another request."); const title = cleanMessage(body.title).slice(0, 100), artist = cleanMessage(body.artist).slice(0, 80); if (!title) return this.error(ws, "Enter a track title."); const request = { id: crypto.randomUUID(), title, artist, name: state.name, status: "pending", createdAt: now }; this.ctx.storage.sql.exec("INSERT INTO requests (id,title,artist,name,status,created_at) VALUES (?,?,?,?,?,?)", request.id, title, artist, state.name, "pending", now); state.requestAt = now; ws.serializeAttachment(state); this.broadcast({ type: "request_added", request }); return; }
    if (body.type === "moderator_auth") { if (!this.env.MODERATOR_KEY || !await safeEqual(String(body.key || ""), this.env.MODERATOR_KEY)) return this.error(ws, "Invalid host key."); state.moderator = state.verified = true; state.name = "EBMARAH"; ws.serializeAttachment(state); ws.send(JSON.stringify({ type: "moderator" })); return; }
    if (body.type === "schedule_set") { if (!state.moderator) return this.error(ws, "Host access required."); const input = body.schedule || {}, start = Number(input.start) || 0, end = Number(input.end) || 0, schedule: Schedule = { title: cleanMessage(input.title).slice(0, 80), host: cleanName(input.host, "ALLTHINGS140"), details: cleanMessage(input.details).slice(0, 180), start, end }; if (!schedule.title || !start || end <= start) return this.error(ws, "Enter a valid title, start, and end time."); await this.ctx.storage.put("schedule", schedule); this.broadcast({ type: "schedule", schedule }); return; }
    if (body.type === "moderate") { if (!state.moderator) return this.error(ws, "Moderator access required."); return this.moderate(body); } if (body.type === "request_action") { if (!state.moderator) return this.error(ws, "Moderator access required."); const id = String(body.requestId || ""), status = String(body.action || ""); if (!["approved", "dismissed"].includes(status)) return this.error(ws, "Invalid request action."); this.ctx.storage.sql.exec("UPDATE requests SET status=? WHERE id=?", status, id); this.broadcast({ type: "request_updated", id, status }); return; }
    if (body.type !== "message") return this.error(ws, "Unknown action."); if (!state.userId) return this.error(ws, "Sign in to join Green Room."); const policy = await this.rpc<{ allowed: boolean; reason: string }>("green_room_can_post", state.authToken); if (!policy?.allowed) return this.error(ws, policy?.reason === "terms_acceptance_required" ? `Accept the current Green Room Terms (${TERMS_VERSION}) before posting.` : `Posting unavailable: ${policy?.reason || "account policy"}.`); if (state.muted) return this.error(ws, "You have been muted by a host."); const now = Date.now(); state.recent = state.recent.filter(ts => now - ts < 10000); if (state.recent.length >= 4 || (state.recent.at(-1) && now - state.recent.at(-1)! < 800)) return this.error(ws, "Slow down for a moment."); let text = cleanMessage(body.text); if (!text) return this.error(ws, "Type a message first."); if ((text.match(URL_RE) || []).length > 1) return this.error(ws, "Only one link is allowed per message."); if (text.toLocaleLowerCase() === state.lastText && now - state.lastTextAt < 30000) return this.error(ws, "Please don’t repeat the same message."); text = text.replace(BLOCKED_RE, "***"); const msg: StoredMessage = { id: crypto.randomUUID(), name: state.name, text, ts: now, expiresAt: now + PUBLIC_TTL, color: state.color, verified: state.verified, senderId: state.userId, avatarPath: state.avatarPath }; this.ctx.storage.sql.exec("INSERT INTO messages (id,name,text,created_at,color,verified,sender_id,expires_at,avatar_path) VALUES (?,?,?,?,?,?,?,?,?)", msg.id, msg.name, msg.text, msg.ts, msg.color, msg.verified ? 1 : 0, msg.senderId, msg.expiresAt, msg.avatarPath || null); state.recent.push(now); state.lastText = text.toLocaleLowerCase(); state.lastTextAt = now; ws.serializeAttachment(state); this.broadcastVisible({ type: "message", message: msg }); await this.scheduleNextExpiry(); }
  async webSocketClose(ws: WebSocket, code: number, reason: string) { ws.close(code, reason); this.broadcast({ type: "presence", count: Math.max(0, this.ctx.getWebSockets().length - 1) }); } async webSocketError(ws: WebSocket) { ws.close(1011, "Connection error"); }
  private async authenticate(ws: WebSocket, state: SocketState, token: string) { if (!token || !this.env.SUPABASE_URL || !this.env.SUPABASE_PUBLIC_KEY) return this.error(ws, "Account authentication is temporarily unavailable."); const user = await this.supabaseUser(token); if (!user?.id) return this.error(ws, "Your session could not be verified."); const profile = await this.profile(token, user.id); if (!profile?.username) return this.error(ws, "Complete your ALLTHINGS140 profile before joining Green Room."); const moderator = await this.rpc<boolean>("green_room_is_moderator", token); state.authToken = token; state.userId = user.id; state.name = profile.username; state.avatarPath = profile.avatar_path || null; state.accountStatus = profile.account_status; state.blockedIds = await this.blocks(token); state.moderator = moderator === true; state.verified = true; ws.serializeAttachment(state); ws.send(JSON.stringify({ type: "auth_state", authenticated: true, userId: state.userId, username: state.name, avatarPath: state.avatarPath, accountStatus: state.accountStatus, moderator: state.moderator, termsVersion: TERMS_VERSION, blockedUserIds: state.blockedIds })); await this.sendHistory(ws, state); }
  private async acceptTerms(ws: WebSocket, state: SocketState) { if (!state.userId) return this.error(ws, "Sign in before accepting the Green Room Terms."); const result = await this.rpc("accept_green_room_terms", state.authToken, { p_terms_version: TERMS_VERSION }); if (!result) return this.error(ws, "Terms acceptance could not be saved."); ws.send(JSON.stringify({ type: "terms_accepted", termsVersion: TERMS_VERSION })); }
  private async postPolicy(ws: WebSocket, state: SocketState) { const result = await this.rpc<{ allowed: boolean; reason: string }>("green_room_can_post", state.authToken); ws.send(JSON.stringify({ type: "post_policy", ...(result || { allowed: false, reason: "policy_unavailable" }), termsVersion: TERMS_VERSION })); }
  private async report(ws: WebSocket, state: SocketState, body: any) { if (!state.userId) return this.error(ws, "Sign in to report content."); const id = String(body.messageId || ""), row = this.ctx.storage.sql.exec<any>("SELECT id,sender_id,name,text,created_at,expires_at FROM messages WHERE id=?", id).toArray()[0]; if (!row) return this.error(ws, "That message is no longer available for reporting."); if (row.sender_id === state.userId) return this.error(ws, "You cannot report your own message."); const result = await this.rpc("submit_green_room_report", state.authToken, { p_reported_user_id: row.sender_id || null, p_message_id: row.id, p_reason: String(body.reason || "other"), p_reporter_note: cleanMessage(body.note).slice(0, 500), p_message_snapshot: { id: row.id, senderId: row.sender_id, name: row.name, text: row.text, createdAt: row.created_at, expiresAt: row.expires_at } }); if (!result) return this.error(ws, "Report could not be submitted."); ws.send(JSON.stringify({ type: "report_submitted", messageId: id })); }
  private async block(ws: WebSocket, state: SocketState, add: boolean, userId: string) { if (!state.userId || !state.authToken || !/^[0-9a-f-]{36}$/i.test(userId) || userId === state.userId) return this.error(ws, "Invalid block target."); const path = add ? "rest/v1/green_room_blocks" : `rest/v1/green_room_blocks?blocker_user_id=eq.${state.userId}&blocked_user_id=eq.${userId}`; const result = await this.supabaseFetch(path, state.authToken, add ? "POST" : "DELETE", add ? { blocker_user_id: state.userId, blocked_user_id: userId } : undefined, add ? "return=minimal" : undefined); if (!result.ok) return this.error(ws, "Block could not be updated."); state.blockedIds = add ? [...new Set([...state.blockedIds, userId])] : state.blockedIds.filter(id => id !== userId); ws.serializeAttachment(state); ws.send(JSON.stringify({ type: add ? "blocked" : "unblocked", userId })); }
  private async sendHistory(ws: WebSocket, state: SocketState) { const rows = this.ctx.storage.sql.exec<any>("SELECT id,name,text,created_at,color,verified,sender_id,expires_at,avatar_path FROM messages WHERE expires_at > ? ORDER BY created_at DESC LIMIT 50", Date.now()).toArray().reverse(); const requests = state.moderator ? this.ctx.storage.sql.exec<any>("SELECT * FROM requests WHERE status='pending' ORDER BY created_at DESC LIMIT 50").toArray() : []; const schedule = await this.ctx.storage.get<Schedule>("schedule"); ws.send(JSON.stringify({ type: "history", messages: rows.filter(r => !state.blockedIds.includes(r.sender_id)).map(r => ({ id: r.id, name: r.name, text: r.text, ts: r.created_at, expiresAt: r.expires_at, color: r.color, verified: !!r.verified, senderId: r.sender_id, avatarPath: r.avatar_path })), count: this.ctx.getWebSockets().length, name: state.name, schedule: schedule || null, requests: requests.map(r => ({ ...r, createdAt: r.created_at })) })); this.sendStation(ws, state); }
  private async purgeExpired(notify: boolean) { const rows = this.ctx.storage.sql.exec<{ id: string }>("SELECT id FROM messages WHERE expires_at > 0 AND expires_at <= ?", Date.now()).toArray(); if (rows.length) { this.ctx.storage.sql.exec("DELETE FROM messages WHERE expires_at > 0 AND expires_at <= ?", Date.now()); if (notify) for (const row of rows) this.broadcast({ type: "expired", id: row.id }); } await this.scheduleNextExpiry(); }
  private async scheduleNextExpiry() { const row = this.ctx.storage.sql.exec<{ expires_at: number }>("SELECT MIN(expires_at) as expires_at FROM messages WHERE expires_at > ?", Date.now()).toArray()[0]; if (row?.expires_at) await this.ctx.storage.setAlarm(row.expires_at); }
  private async supabaseUser(token: string) { const response = await this.supabaseFetch("auth/v1/user", token); return response.ok ? await response.json() as { id: string } : null; }
  private async profile(token: string, userId: string) { const response = await this.supabaseFetch(`rest/v1/profiles?id=eq.${userId}&select=id,username,avatar_path,account_status&limit=1`, token); const rows = response.ok ? await response.json() as any[] : []; return rows[0] || null; }
  private async blocks(token: string) { const response = await this.supabaseFetch("rest/v1/green_room_blocks?select=blocked_user_id", token); const rows = response.ok ? await response.json() as any[] : []; return rows.map(row => String(row.blocked_user_id)); }
  private async rpc<T = unknown>(name: string, token?: string, body?: unknown): Promise<T | null> { if (!token) return null; const response = await this.supabaseFetch(`rest/v1/rpc/${name}`, token, "POST", body); if (!response.ok) return null; const value = await response.json(); return (Array.isArray(value) ? value[0] || null : value) as T; }
  private async supabaseFetch(path: string, token: string, method = "GET", body?: unknown, preference?: string) { const base = (this.env.SUPABASE_URL || "").replace(/\/$/, ""); return fetch(`${base}/${path}`, { method, headers: { apikey: this.env.SUPABASE_PUBLIC_KEY || "", Authorization: `Bearer ${token}`, "content-type": "application/json", ...(preference ? { Prefer: preference } : {}) }, body: body === undefined ? undefined : JSON.stringify(body) }); }
  private stationData(state: SocketState) { const tracks = this.ctx.storage.sql.exec<any>("SELECT * FROM track_history ORDER BY played_at DESC LIMIT 10").toArray(), current = tracks[0], counts = current ? this.ctx.storage.sql.exec<any>("SELECT reaction,COUNT(*) as count FROM reactions WHERE track_id=? GROUP BY reaction", current.track_id).toArray() : []; return { type: "station_data", tracks: tracks.map((t: any) => ({ trackId: t.track_id, title: t.title, artist: t.artist, playedAt: t.played_at })), trackId: current?.track_id || "", reactions: Object.fromEntries(counts.map((c: any) => [c.reaction, c.count])), myReaction: current ? this.ctx.storage.sql.exec<any>("SELECT reaction FROM reactions WHERE track_id=? AND voter_id=?", current.track_id, state.userId || state.id).toArray()[0]?.reaction || null : null }; }
  private sendStation(ws: WebSocket, state: SocketState) { ws.send(JSON.stringify(this.stationData(state))); }
  private broadcastReactions(trackId: string) { const counts = this.ctx.storage.sql.exec<any>("SELECT reaction,COUNT(*) as count FROM reactions WHERE track_id=? GROUP BY reaction", trackId).toArray(); this.broadcast({ type: "reactions", trackId, reactions: Object.fromEntries(counts.map((c: any) => [c.reaction, c.count])) }); }
  private async refreshStation() { try { const response = await fetch("https://status.ebeinc.online/api/public/status", { headers: { accept: "application/json" } }); if (!response.ok) return; const data = await response.json() as any, id = String(data.current_track_id || data.current_title || "").slice(0, 100), title = cleanMessage(data.current_title).slice(0, 140), artist = cleanMessage(data.current_artist).slice(0, 100); if (id && title) { this.ctx.storage.sql.exec("INSERT OR IGNORE INTO track_history (track_id,title,artist,played_at) VALUES (?,?,?,?)", id, title, artist, Date.now()); this.ctx.storage.sql.exec("DELETE FROM track_history WHERE track_id NOT IN (SELECT track_id FROM track_history ORDER BY played_at DESC LIMIT 20)"); } } catch (error) { console.warn("station_refresh_failed", { error: String(error) }); } }
  private moderate(body: any) { if (body.action === "delete") { const id = String(body.messageId || ""); this.ctx.storage.sql.exec("DELETE FROM messages WHERE id=?", id); this.broadcast({ type: "deleted", id }); return; } if (body.action === "clear") { this.ctx.storage.sql.exec("DELETE FROM messages"); this.broadcast({ type: "cleared" }); return; } if (body.action === "announce") { const text = cleanMessage(body.text); if (text) this.broadcast({ type: "announcement", text }); return; } if (body.action === "mute") { const senderId = String(body.senderId || ""); for (const socket of this.ctx.getWebSockets()) { const other = socket.deserializeAttachment() as SocketState | null; if (other?.id === senderId || other?.userId === senderId) { other.muted = true; socket.serializeAttachment(other); this.error(socket, "A host muted this session."); } } } }
  private broadcastVisible(payload: any) { const data = JSON.stringify(payload), senderId = payload?.message?.senderId; for (const socket of this.ctx.getWebSockets()) try { const state = socket.deserializeAttachment() as SocketState | null; if (!state?.blockedIds.includes(senderId)) socket.send(data); } catch (error) { console.warn("chat_broadcast_failed", { error: String(error) }); } }
  private broadcast(payload: unknown) { const data = JSON.stringify(payload); for (const socket of this.ctx.getWebSockets()) try { socket.send(data); } catch (error) { console.warn("chat_broadcast_failed", { error: String(error) }); } }
  private error(ws: WebSocket, message: string) { ws.send(JSON.stringify({ type: "error", message })); }
}
