(()=>{"use strict";
const API="https://status.ebeinc.online",$=selector=>document.querySelector(selector);let token=location.hash.slice(1)||sessionStorage.getItem("allthings140-guest-token")||"",stream=null,context=null,analyser=null,recorder=null,sequence=0,uploadQueue=Promise.resolve(),session=null,pollTimer=null,ending=false;
if(location.hash){sessionStorage.setItem("allthings140-guest-token",token);history.replaceState(null,"",location.pathname)}
const headers=extra=>({"X-Guest-Token":token,...extra});
async function api(path,options={}){const response=await fetch(API+path,{cache:"no-store",...options,headers:headers(options.headers||{})});const data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.error||`Connection failed (${response.status})`);return data}
function state(element,text,kind=""){element.textContent=text;element.className="state "+kind}
function invalidate(message){$("#studioPanel").hidden=true;$("#invalidPanel").hidden=false;$("#invalidMessage").textContent=message;clearInterval(pollTimer)}
async function check(){try{session=await api("/api/guest/session");$("#statusLight").classList.add("online");if(!$("#guestName").value)$("#guestName").value=session.guest_name||"Guest DJ";const status=session.status;if(status==="approved"){state($("#approvalState"),"APPROVED — You may begin broadcasting.","good");$("#startBroadcast").disabled=!stream}else if(status==="live"){state($("#approvalState"),"HOST APPROVED", "good");state($("#broadcastState"),"● LIVE ON ALLTHINGS140RADIO","good")}else if(status==="waiting")state($("#approvalState"),"Waiting for the host to approve your takeover…");else if(["revoked","expired","ended"].includes(status)){if(recorder)stopBroadcast(false);invalidate(`This guest session is ${status}.`)}else state($("#approvalState"),"Connect audio and request host approval.")}catch(error){$("#statusLight").classList.remove("online");if(!session)invalidate(error.message)}}
function stopAudio(){if(stream)stream.getTracks().forEach(track=>track.stop());stream=null;if(context)context.close();context=null;analyser=null}
async function connectAudio(deviceId=""){stopAudio();const constraints={audio:{deviceId:deviceId?{exact:deviceId}:undefined,echoCancellation:false,noiseSuppression:false,autoGainControl:false},video:false};stream=await navigator.mediaDevices.getUserMedia(constraints);context=new AudioContext();const source=context.createMediaStreamSource(stream);analyser=context.createAnalyser();analyser.fftSize=256;source.connect(analyser);drawMeter();const devices=(await navigator.mediaDevices.enumerateDevices()).filter(device=>device.kind==="audioinput");const select=$("#audioDevice");select.replaceChildren();devices.forEach(device=>{const option=document.createElement("option");option.value=device.deviceId;option.textContent=device.label||"Audio input";select.append(option)});select.value=stream.getAudioTracks()[0].getSettings().deviceId||"";select.hidden=false;$("#requestAccess").disabled=false;$("#startBroadcast").disabled=session?.status!=="approved";$("#audioState").textContent="AUDIO CONNECTED — PLAY TRAKTOR TO CHECK THE METER"}
function drawMeter(){if(!analyser)return;const samples=new Uint8Array(analyser.frequencyBinCount);analyser.getByteFrequencyData(samples);const peak=Math.min(100,Math.max(...samples)/255*115);$("#meterFill").style.width=peak+"%";requestAnimationFrame(drawMeter)}
async function requestAccess(){try{await api("/api/guest/join",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({guest_name:$("#guestName").value.trim()||"Guest DJ"})});state($("#approvalState"),"Request sent. Waiting for host approval…");check()}catch(error){state($("#approvalState"),error.message,"bad")}}
function supportedMime(){return ["audio/webm;codecs=opus","audio/webm"].find(type=>MediaRecorder.isTypeSupported(type))||""}
function sendChunk(blob,currentSequence){uploadQueue=uploadQueue.then(async()=>{const response=await fetch(API+"/api/guest/audio",{method:"POST",headers:headers({"Content-Type":"audio/webm","X-Audio-Sequence":String(currentSequence)}),body:blob});const data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.error||"Audio upload failed")}).catch(error=>{state($("#broadcastState"),error.message,"bad");stopBroadcast(false)})}
function startBroadcast(){const mime=supportedMime();if(!stream)return state($("#broadcastState"),"Connect an audio input first.","bad");if(!mime)return state($("#broadcastState"),"Use current Chrome, Edge, or Brave for guest broadcasting.","bad");sequence=0;ending=false;uploadQueue=Promise.resolve();recorder=new MediaRecorder(stream,{mimeType:mime,audioBitsPerSecond:128000});recorder.ondataavailable=event=>{if(event.data.size)sendChunk(event.data,sequence++)};recorder.onstop=()=>{if(ending)uploadQueue.finally(()=>api("/api/guest/end",{method:"POST"}).catch(()=>{}))};recorder.start(1000);$("#startBroadcast").hidden=true;$("#stopBroadcast").hidden=false;$(".live-step").classList.add("active");state($("#broadcastState"),"CONNECTING LIVE AUDIO…","good")}
function stopBroadcast(notify=true){if(!recorder)return;ending=notify;const active=recorder;recorder=null;if(active.state!=="inactive")active.stop();$("#startBroadcast").hidden=false;$("#stopBroadcast").hidden=true;$("#startBroadcast").disabled=true;$(".live-step").classList.remove("active");state($("#broadcastState"),notify?"Broadcast ended. AutoDJ is returning.":"Broadcast connection stopped.")}
$("#connectAudio").onclick=()=>connectAudio().catch(error=>state($("#approvalState"),error.message,"bad"));$("#audioDevice").onchange=event=>connectAudio(event.target.value).catch(error=>state($("#approvalState"),error.message,"bad"));$("#requestAccess").onclick=requestAccess;$("#startBroadcast").onclick=startBroadcast;$("#stopBroadcast").onclick=()=>stopBroadcast(true);window.addEventListener("pagehide",()=>{if(recorder)stopBroadcast(true);stopAudio()});
if(!token)invalidate("This private invitation is missing its access token.");else{check();pollTimer=setInterval(check,2000)}
})();
